WARN = '⚠️'
INFO = 'ℹ️'
ERROR = '❌'
SUCCESS = '✅'
PLUS = '➕'
MINUS = '➖'
LEFT_ARROW = '⬅️'
RIGHT_ARROW = '➡️'
UP_ARROW = '⬆️'
DOWN_ARROW = '⬇️'

CONTRIBUTOR = '👨‍💻'
COMMIT = '⬆️'
DIRECTORY_TREE = '📁'
RULES = '📜'
VIOLATED_RULES = '🚫'
REMOTE_REPOSITORY = '🌐'
ISSUES = '📋'
FILE_GROUP = '📦'
PULL_REQUESTS = '🔄'
PERCENTAGE = '📊'
WEIGHT = '🏆'
SEMANTICS = '📚'
SYNTAX = '📖'

NUMBERS = ['0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣']